Repository Dayana196/Pagina_Web_Carros, pull requests merged in 2025-08, with the labels that each got.

#9 :rocket: Creacion de pagina principal
  css/style.css
  index.html
  src/img/carro33_.jpg
  src/img/logo.png
Labels: Diseño :3

#10 :rocket: Implementacion del dashboard
  .vscode/settings.json
  pag1/css/style.css
  pag1/index.html
  pag1/src/img/assetsMAIN.svg
  pag1/src/img/bmw.svg
  pag1/src/img/bookingMAIN.svg
  pag1/src/img/cuadroline.svg
  pag1/src/img/dashboardMAIN.svg
  pag1/src/img/lamborghini.svg
  pag1/src/img/logoMAIN.svg
  pag1/src/img/logoutMAIN.svg
  pag1/src/img/mercedesbenz.svg
  pag1/src/img/pht-bmw.svg
  pag1/src/img/pht-jeeprubicon.svg
  pag1/src/img/pht-lamborghini.svg
  pag1/src/img/pht-mercedesbenz.svg
  pag1/src/img/pht-porsche.svg
  pag1/src/img/pht-volvo.svg
  pag1/src/img/raio.svg
  pag1/src/img/sellcarsMAIN.svg
  pag1/src/img/servicesMAIN.svg
  pag1/src/img/settingsMAIN.svg
  pag1/src/img/tuerca.svg
  pag1/src/img/vector.svg
  pag1/src/img/volvo.svg
Labels: Panel principal

#14 :zap: Mejoramiento del codigo
  css/dashboard.css
  pag1/dashboard.html
Labels: Panel principal

#15 :rocket: Implementamos inicio de seccion
  css/inicioseccion.css
  index.html
  pag1/inicioseccion.html
Labels: inicio sección

#16 :rocket: Se crea la pagina del Booking
  .vscode/settings.json
  css/Booking.css
  css/dashboard.css
  index.html
  pag1/Booking.html
  pag1/css/style.css
  pag1/dashboard.html
  pag1/src/img/assetsMAIN.svg
  pag1/src/img/bmw.svg
  pag1/src/img/bookingMAIN.svg
  pag1/src/img/cuadroline.svg
  pag1/src/img/dashboardMAIN.svg
  pag1/src/img/lamborghini.svg
  pag1/src/img/logoMAIN.svg
  pag1/src/img/logoutMAIN.svg
  pag1/src/img/mercedesbenz.svg
  pag1/src/img/pht-bmw.svg
  pag1/src/img/pht-jeeprubicon.svg
  pag1/src/img/pht-lamborghini.svg
  pag1/src/img/pht-mercedesbenz.svg
  pag1/src/img/pht-porsche.svg
  pag1/src/img/pht-volvo.svg
  pag1/src/img/raio.svg
  pag1/src/img/sellcarsMAIN.svg
  pag1/src/img/servicesMAIN.svg
  pag1/src/img/settingsMAIN.svg
  pag1/src/img/tuerca.svg
  pag1/src/img/vector.svg
  pag1/src/img/volvo.svg
  src/img/active.png
  src/img/iconperfil.jpg
  src/img/iconperfil.png
  src/img/man.png
Labels: Booking

#18 :rocket: Implementamos pagina de services
  css/service.css
  pag1/service.html
  src/img/buttonpay.png
  src/img/buttons.svg
  src/img/circle.svg
  src/img/cuadro-abajo.png
  src/img/cuadro-req.png
  src/img/rectangle1.png
  src/img/rectangle2.png
  src/img/rectangle3.png
  src/img/rectangle4.png
  src/img/schedule.png
  src/img/text-buttons.svg
Labels: Services

#20 :art: Se modifico parte del diseño y html (creacion de Assets)
  css/Assets.css
  css/BMW.css
  index.html
  pag1/Assets.html
  pag1/BMW.html
  pag1/Booking.html
  pag1/dashboard.html
  pag1/index.html
  src/img/image 64.png
  src/img/image 65.png
  src/img/image 66.png
  src/img/image 68.png
  src/img/ladocars.png
  src/img/princar.png
  src/img/volvo x.png
Labels: Gallery

#23 :sparkles: Creación del Readme
  README.md
  css/style2.css
  pag1/Booking.html
  pag1/Settings.html
  pag1/dashboard.html
  pag1/service.html
Labels: README

#25 6 sell cars
  index.html
  pag1/Assets.html
  pag1/BMW.html
  pag1/Booking.html
  pag1/Mercedez.html
  pag1/SellCars.html
  pag1/Settings.html
  pag1/Volvo.html
  pag1/dashboard.html
  pag1/lamborghini.html
  pag1/service.html
Labels: Sell cars
